/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./*.js"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-background": "#292524",
          "on-secondary-fixed": "#292524",
          "surface-container-lowest": "#ffffff",
          "error-container": "#fee2e2",
          "outline": "#d6d3d1",
          "on-tertiary": "#ffffff",
          "primary": "#273e36",
          "tertiary-fixed": "#d3e4fe",
          "inverse-surface": "#1c1917",
          "outline-variant": "#e7e5e4",
          "surface-container-low": "#f4f1eb",
          "surface-container-highest": "#d6d3d1",
          "tertiary-container": "#e0e7ff",
          "on-surface": "#292524",
          "surface-tint": "#273e36",
          "surface-container-high": "#e7e5e4",
          "surface-variant": "#f5f5f4",
          "on-tertiary-fixed-variant": "#44403c",
          "on-primary-fixed-variant": "#273e36",
          "surface-dim": "#d6d3d1",
          "secondary-fixed-dim": "#a8a29e",
          "background": "#f4f1eb",
          "on-secondary": "#ffffff",
          "tertiary-fixed-dim": "#c7d2fe",
          "surface-container": "#f5f5f4",
          "surface": "#ffffff",
          "on-error-container": "#7f1d1d",
          "tertiary": "#4f46e5",
          "secondary": "#57534e",
          "on-tertiary-container": "#312e81",
          "error": "#dc2626",
          "primary-container": "#dbeafe",
          "inverse-on-surface": "#f4f1eb",
          "on-primary-container": "#273e36",
          "primary-fixed": "#bfdbfe",
          "on-secondary-fixed-variant": "#44403c",
          "secondary-fixed": "#e7e5e4",
          "inverse-primary": "#60a5fa",
          "primary-fixed-dim": "#93c5fd",
          "on-error": "#ffffff",
          "on-secondary-container": "#1c1917",
          "on-primary-fixed": "#273e36",
          "secondary-container": "#d6d3d1",
          "on-primary": "#ffffff",
          "surface-bright": "#ffffff",
          "on-surface-variant": "#57534e",
          "on-tertiary-fixed": "#1e1b4b"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "margin-tablet": "32px",
          "container-max": "1280px",
          "margin-desktop": "64px",
          "unit": "8px",
          "margin-mobile": "16px",
          "gutter": "24px"
      },
      "fontFamily": {
          "headline-lg": ["IBM Plex Sans"],
          "headline-md": ["IBM Plex Sans"],
          "headline-sm": ["IBM Plex Sans"],
          "label-sm": ["Inter"],
          "body-lg": ["Inter"],
          "body-md": ["Inter"],
          "headline-lg-mobile": ["IBM Plex Sans"],
          "label-md": ["Inter"],
          "body-sm": ["Inter"]
      },
      "fontSize": {
          "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "500"}],
          "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}],
          "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "500"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
          "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
