/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./*.js"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-background": "#191c1e",
          "on-secondary-fixed": "#0d1c2f",
          "surface-container-lowest": "#ffffff",
          "error-container": "#ffdad6",
          "outline": "#76777d",
          "on-tertiary": "#ffffff",
          "primary": "#000000",
          "tertiary-fixed": "#d3e4fe",
          "inverse-surface": "#2d3133",
          "outline-variant": "#c6c6cd",
          "surface-container-low": "#f2f4f6",
          "surface-container-highest": "#e0e3e5",
          "tertiary-container": "#0b1c30",
          "on-surface": "#191c1e",
          "surface-tint": "#565e74",
          "surface-container-high": "#e6e8ea",
          "surface-variant": "#e0e3e5",
          "on-tertiary-fixed-variant": "#38485d",
          "on-primary-fixed-variant": "#3f465c",
          "surface-dim": "#d8dadc",
          "secondary-fixed-dim": "#b9c7e0",
          "background": "#f7f9fb",
          "on-secondary": "#ffffff",
          "tertiary-fixed-dim": "#b7c8e1",
          "surface-container": "#eceef0",
          "surface": "#f7f9fb",
          "on-error-container": "#93000a",
          "tertiary": "#000000",
          "secondary": "#515f74",
          "on-tertiary-container": "#75859d",
          "error": "#ba1a1a",
          "primary-container": "#131b2e",
          "inverse-on-surface": "#eff1f3",
          "on-primary-container": "#7c839b",
          "primary-fixed": "#dae2fd",
          "on-secondary-fixed-variant": "#3a485c",
          "secondary-fixed": "#d5e3fd",
          "inverse-primary": "#bec6e0",
          "primary-fixed-dim": "#bec6e0",
          "on-error": "#ffffff",
          "on-secondary-container": "#57657b",
          "on-primary-fixed": "#131b2e",
          "secondary-container": "#d5e3fd",
          "on-primary": "#ffffff",
          "surface-bright": "#f7f9fb",
          "on-surface-variant": "#45464d",
          "on-tertiary-fixed": "#0b1c30"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "margin-tablet": "32px",
          "container-max": "1280px",
          "margin-desktop": "64px",
          "unit": "8px",
          "margin-mobile": "16px",
          "gutter": "24px"
      },
      "fontFamily": {
          "headline-lg": ["IBM Plex Sans"],
          "headline-md": ["IBM Plex Sans"],
          "headline-sm": ["IBM Plex Sans"],
          "label-sm": ["Inter"],
          "body-lg": ["Inter"],
          "body-md": ["Inter"],
          "headline-lg-mobile": ["IBM Plex Sans"],
          "label-md": ["Inter"],
          "body-sm": ["Inter"]
      },
      "fontSize": {
          "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "500"}],
          "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}],
          "label-sm": ["12px", {"lineHeight": "1", "fontWeight": "500"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
          "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
          "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
